```mermaid
graph LR
  subgraph C1["UConn/BU (Safe-Robust CAV)"]
    FeiMiao["Fei Miao (6)"]
    ShaofengZou["Shaofeng Zou (5)"]
    SihongHe["Sihong He (4)"]
    YueWang["Yue Wang (4)"]
    YanchaoSun["Yanchao Sun (3)"]
    FurongHuang["Furong Huang (3)"]
    ShuoHan["Shuo Han (3)"]
    ZhiliZhang["Zhili Zhang (2)"]
    EhsanSabouni["Ehsan Sabouni (2)"]
    WenchaoLi["Wenchao Li (2)"]
    SongHan["Song Han (2)"]
    YiZhou["Yi Zhou (2)"]
    AlvaroVelasquez["Alvaro Velasquez (2)"]
    SongyangHan["Songyang Han (2)"]
    SanbaoSu["Sanbao Su (2)"]
  end
  subgraph C2["Beihang/PKU (Adversarial c-MARL)"]
    YaodongYang["Yaodong Yang (5)"]
    SiminLi["Simin Li (5)"]
    JunGuo["Jun Guo (4)"]
    BoAn["Bo An (4)"]
    XianglongLiu["Xianglong Liu (4)"]
    JingqiaoXiu["Jingqiao Xiu (3)"]
    YuweiZheng["Yuwei Zheng (2)"]
    PuFeng["Pu Feng (2)"]
    XinYu["Xin Yu (2)"]
    JiakaiWang["Jiakai Wang (2)"]
    AishanLiu["Aishan Liu (2)"]
    RuixiaoXu["Ruixiao Xu (2)"]
  end
  subgraph C3["Caltech/CMU Theory (RMG, RQE)"]
    EricMazumdar["Eric Mazumdar (8)"]
    LaixiShi["Laixi Shi (6)"]
    YuejieChi["Yuejie Chi (4)"]
    AdamWierman["Adam Wierman (4)"]
    KishanPanaganti["Kishan Panaganti (3)"]
    JingchuGai["Jingchu Gai (2)"]
  end
  subgraph C4["Tongji/Monmouth (State-Adversarial)"]
    GuanjunLiu["Guanjun Liu (7)"]
    ZiyuanZhou["Ziyuan Zhou (7)"]
    WeiranGuo["Weiran Guo (4)"]
    JiacunWang["Jiacun Wang (3)"]
    MengChuZhou["MengChu Zhou (2)"]
  end
  subgraph C5["EpiSys/Boeing (Military Routing)"]
    SaeedKaviani["Saeed Kaviani (2)"]
    BoRyu["Bo Ryu (2)"]
    EjazAhmed["Ejaz Ahmed (2)"]
    KevinLarson["Kevin Larson (2)"]
    AnhLe["Anh Le (2)"]
    AlexYahja["Alex Yahja (2)"]
    JaeHKim["Jae H. Kim (2)"]
  end
  subgraph C6["Nanjing U/Polixir (Comm-Robust)"]
    LeiYuan["Lei Yuan (3)"]
    FengChen["Feng Chen (3)"]
    YangYu["Yang Yu (3)"]
    ZongzhangZhang["Zongzhang Zhang (2)"]
    LiheLi["Lihe Li (2)"]
  end
  subgraph C7["Wisconsin (Poisoning/Game Theory)"]
    JeremyMcMahan["Jeremy McMahan (3)"]
    QiaominXie["Qiaomin Xie (3)"]
    YoungWu["Young Wu (2)"]
    XiaojinZhu["Xiaojin Zhu (2)"]
  end
  subgraph C8["Aalto (Robustness eval)"]
    WenshuaiZhao["Wenshuai Zhao (2)"]
    EetuAleksiRantala["Eetu-Aleksi Rantala (2)"]
    SaharSalimpour["Sahar Salimpour (2)"]
    JoniPajarinen["Joni Pajarinen (2)"]
    JorgePeaQueralta["Jorge Peña-Queralta (2)"]
  end
  subgraph C9["Team: Yuchen Shi"]
    YuchenShi["Yuchen Shi (2)"]
    HuaxinPei["Huaxin Pei (2)"]
    YiZhang["Yi Zhang (2)"]
    DanyaYao["Danya Yao (2)"]
  end
  subgraph C10["Adelaide/DST (Defence)"]
    MaxwellStanden["Maxwell Standen (2)"]
    JunaeKim["Junae Kim (2)"]
    ClaudiaSzabo["Claudia Szabo (2)"]
  end
  subgraph C11["UNIST? (per-paper)"]
    SunwooLee["Sunwoo Lee (2)"]
    YonghyeonJo["Yonghyeon Jo (2)"]
    SeungyulHan["Seungyul Han (2)"]
  end
  subgraph C12["Team: Zhenyu Pan"]
    ZhenyuPan["Zhenyu Pan (2)"]
    YitingZhang["Yiting Zhang (2)"]
    HaozhengLuo["Haozheng Luo (2)"]
  end
  subgraph C13["Simula (AV robustness eval)"]
    AizazSharif["Aizaz Sharif (2)"]
    DusicaMarijan["Dusica Marijan (2)"]
  end
  subgraph C14["Cambridge/Prorok (Swarm GNN)"]
    JanBlumenkamp["Jan Blumenkamp (2)"]
    AmandaProrok["Amanda Prorok (2)"]
  end
  subgraph C15["UC Davis (Poisoning)"]
    GuanlinLiu["Guanlin Liu (2)"]
    LifengLai["Lifeng Lai (2)"]
  end
  subgraph C16["Team: Haejoon Lee"]
    HaejoonLee["Haejoon Lee (2)"]
    DimitraPanagou["Dimitra Panagou (2)"]
  end
  subgraph C17["Team: Stuart Russell"]
    StuartRussell["Stuart Russell (2)"]
    FeiFang["Fei Fang (2)"]
  end
  subgraph C18["Team: Jieyu Lin"]
    JieyuLin["Jieyu Lin (2)"]
    SaiQianZhang["Sai Qian Zhang (2)"]
  end
  GuanjunLiu -- 7 --- ZiyuanZhou
  EricMazumdar -- 5 --- LaixiShi
  JunGuo -- 4 --- SiminLi
  SiminLi -- 4 --- XianglongLiu
  AdamWierman -- 4 --- EricMazumdar
  GuanjunLiu -- 4 --- WeiranGuo
  WeiranGuo -- 4 --- ZiyuanZhou
  FurongHuang -- 3 --- YanchaoSun
  EricMazumdar -- 3 --- KishanPanaganti
  GuanjunLiu -- 3 --- JiacunWang
  JiacunWang -- 3 --- ZiyuanZhou
  JingqiaoXiu -- 3 --- SiminLi
  JingqiaoXiu -- 3 --- XianglongLiu
  JingqiaoXiu -- 3 --- YaodongYang
  JunGuo -- 3 --- XianglongLiu
  SiminLi -- 3 --- YaodongYang
  XianglongLiu -- 3 --- YaodongYang
  FeiMiao -- 3 --- ShaofengZou
  FeiMiao -- 3 --- ShuoHan
  FeiMiao -- 3 --- SihongHe
  ShaofengZou -- 3 --- ShuoHan
  ShaofengZou -- 3 --- SihongHe
  ShuoHan -- 3 --- SihongHe
  JeremyMcMahan -- 3 --- QiaominXie
  FengChen -- 3 --- LeiYuan
  FengChen -- 3 --- YangYu
  LeiYuan -- 3 --- YangYu
  AdamWierman -- 3 --- LaixiShi
  AdamWierman -- 3 --- YuejieChi
  EricMazumdar -- 3 --- YuejieChi
  LaixiShi -- 3 --- YuejieChi
  AizazSharif -- 2 --- DusicaMarijan
  EhsanSabouni -- 2 --- FeiMiao
  EhsanSabouni -- 2 --- WenchaoLi
  EhsanSabouni -- 2 --- ZhiliZhang
  FeiMiao -- 2 --- WenchaoLi
  FeiMiao -- 2 --- ZhiliZhang
  WenchaoLi -- 2 --- ZhiliZhang
  FeiMiao -- 2 --- SongHan
  KishanPanaganti -- 2 --- LaixiShi
  AlexYahja -- 2 --- AnhLe
  AlexYahja -- 2 --- BoRyu
  AlexYahja -- 2 --- EjazAhmed
  AlexYahja -- 2 --- JaeHKim
  AlexYahja -- 2 --- KevinLarson
  AlexYahja -- 2 --- SaeedKaviani
  AnhLe -- 2 --- BoRyu
  AnhLe -- 2 --- EjazAhmed
  AnhLe -- 2 --- JaeHKim
  AnhLe -- 2 --- KevinLarson
  AnhLe -- 2 --- SaeedKaviani
  BoRyu -- 2 --- EjazAhmed
  BoRyu -- 2 --- JaeHKim
  BoRyu -- 2 --- KevinLarson
  BoRyu -- 2 --- SaeedKaviani
  EjazAhmed -- 2 --- JaeHKim
  EjazAhmed -- 2 --- KevinLarson
  EjazAhmed -- 2 --- SaeedKaviani
  JaeHKim -- 2 --- KevinLarson
  JaeHKim -- 2 --- SaeedKaviani
  KevinLarson -- 2 --- SaeedKaviani
  AmandaProrok -- 2 --- JanBlumenkamp
  ShaofengZou -- 2 --- YiZhou
  AishanLiu -- 2 --- JiakaiWang
  AishanLiu -- 2 --- JingqiaoXiu
  AishanLiu -- 2 --- JunGuo
  AishanLiu -- 2 --- SiminLi
  AishanLiu -- 2 --- XianglongLiu
  AishanLiu -- 2 --- XinYu
  AishanLiu -- 2 --- YaodongYang
  BoAn -- 2 --- JingqiaoXiu
  BoAn -- 2 --- PuFeng
  BoAn -- 2 --- SiminLi
  BoAn -- 2 --- XianglongLiu
  BoAn -- 2 --- YaodongYang
  BoAn -- 2 --- YuweiZheng
  JiakaiWang -- 2 --- JingqiaoXiu
  JiakaiWang -- 2 --- JunGuo
  JiakaiWang -- 2 --- SiminLi
  JiakaiWang -- 2 --- XianglongLiu
  JiakaiWang -- 2 --- XinYu
  JiakaiWang -- 2 --- YaodongYang
  JingqiaoXiu -- 2 --- JunGuo
  JingqiaoXiu -- 2 --- PuFeng
  JingqiaoXiu -- 2 --- XinYu
  JingqiaoXiu -- 2 --- YuweiZheng
  JunGuo -- 2 --- XinYu
  JunGuo -- 2 --- YaodongYang
  PuFeng -- 2 --- SiminLi
  PuFeng -- 2 --- XianglongLiu
  PuFeng -- 2 --- YaodongYang
  PuFeng -- 2 --- YuweiZheng
  SiminLi -- 2 --- XinYu
  SiminLi -- 2 --- YuweiZheng
  XianglongLiu -- 2 --- XinYu
  XianglongLiu -- 2 --- YuweiZheng
  XinYu -- 2 --- YaodongYang
  YaodongYang -- 2 --- YuweiZheng
  ShaofengZou -- 2 --- YueWang
  ClaudiaSzabo -- 2 --- JunaeKim
  ClaudiaSzabo -- 2 --- MaxwellStanden
  JunaeKim -- 2 --- MaxwellStanden
  GuanlinLiu -- 2 --- LifengLai
  FengChen -- 2 --- ZongzhangZhang
  LeiYuan -- 2 --- ZongzhangZhang
  YangYu -- 2 --- ZongzhangZhang
  EetuAleksiRantala -- 2 --- JoniPajarinen
  EetuAleksiRantala -- 2 --- JorgePeaQueralta
  EetuAleksiRantala -- 2 --- SaharSalimpour
  EetuAleksiRantala -- 2 --- WenshuaiZhao
  JoniPajarinen -- 2 --- JorgePeaQueralta
  JoniPajarinen -- 2 --- SaharSalimpour
  JoniPajarinen -- 2 --- WenshuaiZhao
  JorgePeaQueralta -- 2 --- SaharSalimpour
  JorgePeaQueralta -- 2 --- WenshuaiZhao
  SaharSalimpour -- 2 --- WenshuaiZhao
  DimitraPanagou -- 2 --- HaejoonLee
  JeremyMcMahan -- 2 --- XiaojinZhu
  JeremyMcMahan -- 2 --- YoungWu
  QiaominXie -- 2 --- XiaojinZhu
  QiaominXie -- 2 --- YoungWu
  XiaojinZhu -- 2 --- YoungWu
  FeiMiao -- 2 --- SanbaoSu
  FeiMiao -- 2 --- SongyangHan
  SanbaoSu -- 2 --- ShaofengZou
  SanbaoSu -- 2 --- ShuoHan
  SanbaoSu -- 2 --- SihongHe
  SanbaoSu -- 2 --- SongyangHan
  ShaofengZou -- 2 --- SongyangHan
  ShuoHan -- 2 --- SongyangHan
  SihongHe -- 2 --- SongyangHan
  JingqiaoXiu -- 2 --- RuixiaoXu
  RuixiaoXu -- 2 --- SiminLi
  RuixiaoXu -- 2 --- XianglongLiu
  RuixiaoXu -- 2 --- YaodongYang
  JiacunWang -- 2 --- WeiranGuo
  DanyaYao -- 2 --- HuaxinPei
  DanyaYao -- 2 --- YiZhang
  DanyaYao -- 2 --- YuchenShi
  HuaxinPei -- 2 --- YiZhang
  HuaxinPei -- 2 --- YuchenShi
  YiZhang -- 2 --- YuchenShi
  JingchuGai -- 2 --- LaixiShi
  SeungyulHan -- 2 --- SunwooLee
  SeungyulHan -- 2 --- YonghyeonJo
  SunwooLee -- 2 --- YonghyeonJo
  GuanjunLiu -- 2 --- MengChuZhou
  MengChuZhou -- 2 --- WeiranGuo
  MengChuZhou -- 2 --- ZiyuanZhou
  FengChen -- 2 --- LiheLi
  LeiYuan -- 2 --- LiheLi
  LiheLi -- 2 --- YangYu
  JieyuLin -- 2 --- SaiQianZhang
  HaozhengLuo -- 2 --- YitingZhang
  HaozhengLuo -- 2 --- ZhenyuPan
  YitingZhang -- 2 --- ZhenyuPan
  EhsanSabouni --- FurongHuang
  EhsanSabouni --- YanchaoSun
  FeiMiao --- FurongHuang
  FeiMiao --- YanchaoSun
  FurongHuang --- WenchaoLi
  FurongHuang --- ZhiliZhang
  WenchaoLi --- YanchaoSun
  YanchaoSun --- ZhiliZhang
  EhsanSabouni --- SongHan
  SongHan --- WenchaoLi
  SongHan --- ZhiliZhang
  AishanLiu --- BoAn
  AishanLiu --- PuFeng
  AishanLiu --- YuweiZheng
  BoAn --- JiakaiWang
  BoAn --- JunGuo
  BoAn --- XinYu
  JiakaiWang --- PuFeng
  JiakaiWang --- YuweiZheng
  JunGuo --- PuFeng
  JunGuo --- YuweiZheng
  PuFeng --- XinYu
  XinYu --- YuweiZheng
  FeiMiao --- YueWang
  ShuoHan --- YueWang
  SihongHe --- YueWang
  AlvaroVelasquez --- ShaofengZou
  AlvaroVelasquez --- YiZhou
  AlvaroVelasquez --- YueWang
  YiZhou --- YueWang
  BoAn --- RuixiaoXu
  PuFeng --- RuixiaoXu
  RuixiaoXu --- YuweiZheng
  AdamWierman --- JingchuGai
  EricMazumdar --- JingchuGai
  JingchuGai --- YuejieChi
  FeiFang --- StuartRussell
  AdamWierman --- KishanPanaganti
  LiheLi --- ZongzhangZhang
  AishanLiu --- RuixiaoXu
  JiakaiWang --- RuixiaoXu
  JunGuo --- RuixiaoXu
  RuixiaoXu --- XinYu
```